name: Crear Random Browser

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  windows:
    runs-on: windows-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Crear aplicación Windows
        run: npx electron-builder --win

      - name: Guardar aplicación Windows
        uses: actions/upload-artifact@v4
        with:
          name: Random-Browser-Windows
          path: dist/*.exe


  linux:

    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Crear aplicación Linux
        run: npx electron-builder --linux AppImage

      - name: Guardar aplicación Linux
        uses: actions/upload-artifact@v4
        with:
          name: Random-Browser-Linux
          path: dist/*.AppImage
